receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  prometheus_simple:
    collection_interval: 10s
    endpoint: "localhost:8080"
    metrics_path: '/metrics'
    use_service_account: false
exporters:
  debug:
    verbosity: detailed
processors:
  batch: {}

# service:
#   telemetry:
#     metrics:
#       readers:
#         - pull:
#             exporter:
#               prometheus:
#                 host: "host.docker.internal"
#                 port: 8080

service:
  pipelines:
    metrics:
      receivers: [prometheus_simple]
      processors: [batch]
      exporters: [debug]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug]
